// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RichMoneyLoterry.proto

package com.sh.game.proto;

public final class RichMoneyLoterryProtos {
  private RichMoneyLoterryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LotteryInfoNtfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:holidayActivity.LotteryInfoNtf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 loterryTimes = 1;</code>
     *
     * <pre>
     *总摇奖次数
     * </pre>
     */
    boolean hasLoterryTimes();
    /**
     * <code>required int32 loterryTimes = 1;</code>
     *
     * <pre>
     *总摇奖次数
     * </pre>
     */
    int getLoterryTimes();

    /**
     * <code>required int32 usedTimes = 2;</code>
     *
     * <pre>
     *已使用次数
     * </pre>
     */
    boolean hasUsedTimes();
    /**
     * <code>required int32 usedTimes = 2;</code>
     *
     * <pre>
     *已使用次数
     * </pre>
     */
    int getUsedTimes();

    /**
     * <code>required int32 todayOpen = 3;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    boolean hasTodayOpen();
    /**
     * <code>required int32 todayOpen = 3;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    int getTodayOpen();

    /**
     * <code>required int32 test123 = 4;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    boolean hasTest123();
    /**
     * <code>required int32 test123 = 4;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    int getTest123();
  }
  /**
   * Protobuf type {@code holidayActivity.LotteryInfoNtf}
   *
   * <pre>
   *抽奖信息通知
   * </pre>
   */
  public static final class LotteryInfoNtf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:holidayActivity.LotteryInfoNtf)
      LotteryInfoNtfOrBuilder {
    // Use LotteryInfoNtf.newBuilder() to construct.
    private LotteryInfoNtf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LotteryInfoNtf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LotteryInfoNtf defaultInstance;
    public static LotteryInfoNtf getDefaultInstance() {
      return defaultInstance;
    }

    public LotteryInfoNtf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LotteryInfoNtf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loterryTimes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              usedTimes_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              todayOpen_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              test123_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_LotteryInfoNtf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_LotteryInfoNtf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.class, com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.Builder.class);
    }

    public static com.google.protobuf.Parser<LotteryInfoNtf> PARSER =
        new com.google.protobuf.AbstractParser<LotteryInfoNtf>() {
      public LotteryInfoNtf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LotteryInfoNtf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LotteryInfoNtf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LOTERRYTIMES_FIELD_NUMBER = 1;
    private int loterryTimes_;
    /**
     * <code>required int32 loterryTimes = 1;</code>
     *
     * <pre>
     *总摇奖次数
     * </pre>
     */
    public boolean hasLoterryTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 loterryTimes = 1;</code>
     *
     * <pre>
     *总摇奖次数
     * </pre>
     */
    public int getLoterryTimes() {
      return loterryTimes_;
    }

    public static final int USEDTIMES_FIELD_NUMBER = 2;
    private int usedTimes_;
    /**
     * <code>required int32 usedTimes = 2;</code>
     *
     * <pre>
     *已使用次数
     * </pre>
     */
    public boolean hasUsedTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 usedTimes = 2;</code>
     *
     * <pre>
     *已使用次数
     * </pre>
     */
    public int getUsedTimes() {
      return usedTimes_;
    }

    public static final int TODAYOPEN_FIELD_NUMBER = 3;
    private int todayOpen_;
    /**
     * <code>required int32 todayOpen = 3;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    public boolean hasTodayOpen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 todayOpen = 3;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    public int getTodayOpen() {
      return todayOpen_;
    }

    public static final int TEST123_FIELD_NUMBER = 4;
    private int test123_;
    /**
     * <code>required int32 test123 = 4;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    public boolean hasTest123() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 test123 = 4;</code>
     *
     * <pre>
     *今日是否打开活动界面
     * </pre>
     */
    public int getTest123() {
      return test123_;
    }

    private void initFields() {
      loterryTimes_ = 0;
      usedTimes_ = 0;
      todayOpen_ = 0;
      test123_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLoterryTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsedTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTest123()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, loterryTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, usedTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, todayOpen_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, test123_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, loterryTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, usedTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, todayOpen_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, test123_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code holidayActivity.LotteryInfoNtf}
     *
     * <pre>
     *抽奖信息通知
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:holidayActivity.LotteryInfoNtf)
        com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_LotteryInfoNtf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_LotteryInfoNtf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.class, com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.Builder.class);
      }

      // Construct using com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loterryTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        usedTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        todayOpen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        test123_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_LotteryInfoNtf_descriptor;
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf getDefaultInstanceForType() {
        return com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.getDefaultInstance();
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf build() {
        com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf buildPartial() {
        com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf result = new com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loterryTimes_ = loterryTimes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.usedTimes_ = usedTimes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.todayOpen_ = todayOpen_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.test123_ = test123_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf) {
          return mergeFrom((com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf other) {
        if (other == com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf.getDefaultInstance()) return this;
        if (other.hasLoterryTimes()) {
          setLoterryTimes(other.getLoterryTimes());
        }
        if (other.hasUsedTimes()) {
          setUsedTimes(other.getUsedTimes());
        }
        if (other.hasTodayOpen()) {
          setTodayOpen(other.getTodayOpen());
        }
        if (other.hasTest123()) {
          setTest123(other.getTest123());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoterryTimes()) {
          
          return false;
        }
        if (!hasUsedTimes()) {
          
          return false;
        }
        if (!hasTodayOpen()) {
          
          return false;
        }
        if (!hasTest123()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sh.game.proto.RichMoneyLoterryProtos.LotteryInfoNtf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int loterryTimes_ ;
      /**
       * <code>required int32 loterryTimes = 1;</code>
       *
       * <pre>
       *总摇奖次数
       * </pre>
       */
      public boolean hasLoterryTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 loterryTimes = 1;</code>
       *
       * <pre>
       *总摇奖次数
       * </pre>
       */
      public int getLoterryTimes() {
        return loterryTimes_;
      }
      /**
       * <code>required int32 loterryTimes = 1;</code>
       *
       * <pre>
       *总摇奖次数
       * </pre>
       */
      public Builder setLoterryTimes(int value) {
        bitField0_ |= 0x00000001;
        loterryTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 loterryTimes = 1;</code>
       *
       * <pre>
       *总摇奖次数
       * </pre>
       */
      public Builder clearLoterryTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loterryTimes_ = 0;
        onChanged();
        return this;
      }

      private int usedTimes_ ;
      /**
       * <code>required int32 usedTimes = 2;</code>
       *
       * <pre>
       *已使用次数
       * </pre>
       */
      public boolean hasUsedTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 usedTimes = 2;</code>
       *
       * <pre>
       *已使用次数
       * </pre>
       */
      public int getUsedTimes() {
        return usedTimes_;
      }
      /**
       * <code>required int32 usedTimes = 2;</code>
       *
       * <pre>
       *已使用次数
       * </pre>
       */
      public Builder setUsedTimes(int value) {
        bitField0_ |= 0x00000002;
        usedTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 usedTimes = 2;</code>
       *
       * <pre>
       *已使用次数
       * </pre>
       */
      public Builder clearUsedTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        usedTimes_ = 0;
        onChanged();
        return this;
      }

      private int todayOpen_ ;
      /**
       * <code>required int32 todayOpen = 3;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public boolean hasTodayOpen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 todayOpen = 3;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public int getTodayOpen() {
        return todayOpen_;
      }
      /**
       * <code>required int32 todayOpen = 3;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public Builder setTodayOpen(int value) {
        bitField0_ |= 0x00000004;
        todayOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayOpen = 3;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public Builder clearTodayOpen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        todayOpen_ = 0;
        onChanged();
        return this;
      }

      private int test123_ ;
      /**
       * <code>required int32 test123 = 4;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public boolean hasTest123() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 test123 = 4;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public int getTest123() {
        return test123_;
      }
      /**
       * <code>required int32 test123 = 4;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public Builder setTest123(int value) {
        bitField0_ |= 0x00000008;
        test123_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 test123 = 4;</code>
       *
       * <pre>
       *今日是否打开活动界面
       * </pre>
       */
      public Builder clearTest123() {
        bitField0_ = (bitField0_ & ~0x00000008);
        test123_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:holidayActivity.LotteryInfoNtf)
    }

    static {
      defaultInstance = new LotteryInfoNtf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:holidayActivity.LotteryInfoNtf)
  }

  public interface ClickToLoterryAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:holidayActivity.ClickToLoterryAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    boolean hasReward();
    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    java.lang.String getReward();
    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    com.google.protobuf.ByteString
        getRewardBytes();
  }
  /**
   * Protobuf type {@code holidayActivity.ClickToLoterryAck}
   *
   * <pre>
   *手动抽奖响应
   * </pre>
   */
  public static final class ClickToLoterryAck extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:holidayActivity.ClickToLoterryAck)
      ClickToLoterryAckOrBuilder {
    // Use ClickToLoterryAck.newBuilder() to construct.
    private ClickToLoterryAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClickToLoterryAck(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClickToLoterryAck defaultInstance;
    public static ClickToLoterryAck getDefaultInstance() {
      return defaultInstance;
    }

    public ClickToLoterryAck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClickToLoterryAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              reward_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_ClickToLoterryAck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_ClickToLoterryAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.class, com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.Builder.class);
    }

    public static com.google.protobuf.Parser<ClickToLoterryAck> PARSER =
        new com.google.protobuf.AbstractParser<ClickToLoterryAck>() {
      public ClickToLoterryAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClickToLoterryAck(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClickToLoterryAck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REWARD_FIELD_NUMBER = 1;
    private java.lang.Object reward_;
    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    public boolean hasReward() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    public java.lang.String getReward() {
      java.lang.Object ref = reward_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reward_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reward = 1;</code>
     *
     * <pre>
     *获取奖励
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRewardBytes() {
      java.lang.Object ref = reward_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reward_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRewardBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRewardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code holidayActivity.ClickToLoterryAck}
     *
     * <pre>
     *手动抽奖响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:holidayActivity.ClickToLoterryAck)
        com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_ClickToLoterryAck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_ClickToLoterryAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.class, com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.Builder.class);
      }

      // Construct using com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reward_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sh.game.proto.RichMoneyLoterryProtos.internal_static_holidayActivity_ClickToLoterryAck_descriptor;
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck getDefaultInstanceForType() {
        return com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.getDefaultInstance();
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck build() {
        com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck buildPartial() {
        com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck result = new com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reward_ = reward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck) {
          return mergeFrom((com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck other) {
        if (other == com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck.getDefaultInstance()) return this;
        if (other.hasReward()) {
          bitField0_ |= 0x00000001;
          reward_ = other.reward_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReward()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sh.game.proto.RichMoneyLoterryProtos.ClickToLoterryAck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object reward_ = "";
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public boolean hasReward() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public java.lang.String getReward() {
        java.lang.Object ref = reward_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reward_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRewardBytes() {
        java.lang.Object ref = reward_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reward_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public Builder setReward(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public Builder clearReward() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reward_ = getDefaultInstance().getReward();
        onChanged();
        return this;
      }
      /**
       * <code>required string reward = 1;</code>
       *
       * <pre>
       *获取奖励
       * </pre>
       */
      public Builder setRewardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reward_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:holidayActivity.ClickToLoterryAck)
    }

    static {
      defaultInstance = new ClickToLoterryAck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:holidayActivity.ClickToLoterryAck)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_holidayActivity_LotteryInfoNtf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_holidayActivity_LotteryInfoNtf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_holidayActivity_ClickToLoterryAck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_holidayActivity_ClickToLoterryAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RichMoneyLoterry.proto\022\017holidayActivit" +
      "y\"]\n\016LotteryInfoNtf\022\024\n\014loterryTimes\030\001 \002(" +
      "\005\022\021\n\tusedTimes\030\002 \002(\005\022\021\n\ttodayOpen\030\003 \002(\005\022" +
      "\017\n\007test123\030\004 \002(\005\"#\n\021ClickToLoterryAck\022\016\n" +
      "\006reward\030\001 \002(\tB+\n\021com.sh.game.protoB\026Rich" +
      "MoneyLoterryProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_holidayActivity_LotteryInfoNtf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_holidayActivity_LotteryInfoNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_holidayActivity_LotteryInfoNtf_descriptor,
        new java.lang.String[] { "LoterryTimes", "UsedTimes", "TodayOpen", "Test123", });
    internal_static_holidayActivity_ClickToLoterryAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_holidayActivity_ClickToLoterryAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_holidayActivity_ClickToLoterryAck_descriptor,
        new java.lang.String[] { "Reward", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
